"""
Structured report models — Phase 11.

An AnalysisReport is the fully assembled output document for one analysis run.
It is built on-demand from the stored MongoDB analysis result and is never
persisted separately — the raw result document is the source of truth.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field

REPORT_DISCLAIMER = (
    "Results are preliminary. Novelty and contamination flags require expert "
    "confirmation before use in scientific publications. Model predictions are "
    "probabilistic and may contain errors. This report was generated by "
    "Synth Veda and does not constitute a taxonomic authority."
)


# ---------------------------------------------------------------------------
# Sub-sections
# ---------------------------------------------------------------------------

class SampleMetadata(BaseModel):
    analysis_id: str
    job_id: str
    upload_id: str
    user_id: Optional[str]
    mode: str
    source_file: Optional[str]
    created_at: datetime
    model_version_set: Optional[str]


class QCSummary(BaseModel):
    total_sequences: int
    passed_qc: int
    failed_qc: int
    low_quality_count: int
    mean_length: float
    mean_gc_ratio: float
    mean_n_ratio: float
    has_invalid_chars_count: int


class RouteDistributionEntry(BaseModel):
    route: str
    count: int
    fraction: float


class KnownSpeciesEntry(BaseModel):
    sequence_id: str
    predicted_taxon: Optional[str]
    route: str
    confidence: float
    model_version_used: Optional[str]
    reason_codes: list[str]


class PossibleNoveltyEntry(BaseModel):
    sequence_id: str
    route: str
    novelty_score: float
    novelty_level: str
    abyss_recommendation: str
    requires_cloud_confirmation: bool
    reason_codes: list[str]
    contamination_score: float


class ContaminationWarning(BaseModel):
    sequence_id: str
    contamination_type: Optional[str]
    contamination_score: float
    route: str
    reason_codes: list[str]


class BiodiversitySummary(BaseModel):
    """
    Preliminary biodiversity metrics computed from routing + classification.
    These are rough estimates based on model predictions, not curated data.
    """
    total_sequences: int
    route_richness: int          # number of distinct non-low-quality routes
    predicted_taxon_richness: int  # number of distinct predicted_taxon values
    shannon_diversity_index: float  # H = -Σ p_i * ln(p_i) over route groups
    dominant_route: Optional[str]
    novelty_fraction: float      # fraction of sequences with novelty_score >= 0.45
    contamination_fraction: float


class ModelVersionEntry(BaseModel):
    model_version_used: str
    route: str
    sequence_count: int


class ReviewStatusSummary(BaseModel):
    total_reviews: int
    submitted: int
    triaged: int
    needs_evidence: int
    accepted: int
    rejected: int
    duplicate: int
    company_verified: int
    included_in_training_batch: int
    auto_novelty_reviews: int
    auto_contamination_reviews: int


# ---------------------------------------------------------------------------
# Top-level report
# ---------------------------------------------------------------------------

class AnalysisReport(BaseModel):
    report_version: str = "1.0"
    metadata: SampleMetadata
    qc_summary: QCSummary
    route_distribution: list[RouteDistributionEntry]
    known_species: list[KnownSpeciesEntry]
    possible_novelty: list[PossibleNoveltyEntry]
    contamination_warnings: list[ContaminationWarning]
    biodiversity: BiodiversitySummary
    model_versions_used: list[ModelVersionEntry]
    review_status: ReviewStatusSummary
    disclaimer: str = REPORT_DISCLAIMER
    generated_at: datetime = Field(default_factory=datetime.utcnow)
